version: "3.9"

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
