# fly.toml app configuration file generated for hextom-send-stock-price-silent-smoke-3071 on 2025-09-04T16:07:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hextom-send-stock-price-silent-smoke-3071'
primary_region = 'yyz'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
